### ISSUE TITLE
Include font-files and scss in the addon directly

### ISSUE THREAD

**Issue by moberwasserlechner** [vaadin/vaadin-icons-addon#2]
With this I only have to add the maven dependency and recompile the widgetset. No further setup steps required.

**Comment by jouni** [comment]
This should be fixed in the next release: https://github.com/vaadin/vaadin-icons-addon/releases/tag/2.0.0

**Comment by jouni** [comment]
This should be fixed now in the addon. Please report back if it’s not working as expected.

Also, in Framework 8 we will have Vaadin Icons already as a dependency, so you don’t need to do anything to use them.
